const crypto = require('node:crypto');
const DEFAULT_ENDPOINT = 'https://api.deepseek.com/chat/completions';
const DEFAULT_MODEL = 'deepseek-v4-flash';
// Keep the CommonJS runtime on the exact same prompt artifact as Vite/Vercel.
const { STRUCTURE_SYSTEM_PROMPT, REPORT_STRUCTURE_SYSTEM_PROMPT } = require('./src/shared/structurePrompt.cjs');
const SYSTEM_PROMPT = STRUCTURE_SYSTEM_PROMPT;
function normalizeEndpoint(v) { v=String(v||'').trim().replace(/\/+$/,''); return !v?DEFAULT_ENDPOINT:/\/chat\/completions$/i.test(v)?v:v+'/chat/completions'; }
function config(env=process.env, production=false) { const key=String(env.DEEPSEEK_API_KEY||'').trim(); return {apiKey:key, endpoint:production?DEFAULT_ENDPOINT:normalizeEndpoint(env.DEEPSEEK_ENDPOINT), model:production?DEFAULT_MODEL:(String(env.DEEPSEEK_MODEL||DEFAULT_MODEL).trim()||DEFAULT_MODEL), authHeader:production?'Authorization':(String(env.DEEPSEEK_AUTH_HEADER||'Authorization').trim()||'Authorization'), authScheme:production?'Bearer':(env.DEEPSEEK_AUTH_SCHEME===undefined?'Bearer':String(env.DEEPSEEK_AUTH_SCHEME).trim())}; }
function buildPayload(text, mode='items', cfg=config()) { const prompt = mode === 'report' ? REPORT_STRUCTURE_SYSTEM_PROMPT : STRUCTURE_SYSTEM_PROMPT; return {model:cfg.model,messages:[{role:'system',content: prompt},{role:'user',content:text}],temperature:0,thinking:{type:'disabled'}}; }
function textPart(v) { if(typeof v==='string') return v; if(!Array.isArray(v)) return ''; return v.map(p=>typeof p==='string'?p:(p&&typeof p==='object'?(typeof p.text==='string'?p.text:typeof p.content==='string'?p.content:''):'' )).join(''); }
function extractContent(payload) { const m=payload&&Array.isArray(payload.choices)&&payload.choices[0]&&payload.choices[0].message; if(!m||typeof m!=='object') return null; for(const v of [m.content,m.reasoning_content]) { const s=textPart(v); if(s.trim()) return clean(s); } for(const c of (Array.isArray(m.tool_calls)?m.tool_calls:[])) { const a=c&&c.function&&c.function.arguments; if(typeof a==='string'&&a.trim()) return clean(a); } return null; }
function clean(s) { const t=s.trim(); const match=t.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i); return (match?match[1]:t).trim(); }
function errorMessage(status) { if(status===401||status===403)return '识别服务校验未通过：服务端密钥被上游拒绝，请稍后重试。'; if(status===429)return '请求过于频繁，请稍后重试。'; if(status===504)return '识别服务响应超时，请稍后重试。'; if(status===502)return '识别服务暂时无法连接，请稍后重试。'; return '识别服务暂时不可用，请稍后重试。'; }
function fingerprint(key) { return key?crypto.createHash('sha256').update(key).digest('hex').slice(0,8):null; }
function safeError(status, code, id, stage, attempted, key) { const d={errorCode:code,message:errorMessage(status),requestId:id,stage:stage||'handler',upstreamAttempted:!!attempted,upstream:null,model:null,endpoint:null}; if(attempted){d.upstream={host:'api.deepseek.com',authHeader:'Authorization',scheme:'Bearer',keyPresent:!!key,keyFingerprint:fingerprint(key)};d.model=DEFAULT_MODEL;d.endpoint=DEFAULT_ENDPOINT;} return d; }
async function recognize(text, mode, env=process.env, signal) { const cfg=config(env,true); if(!cfg.apiKey) return {status:503,error:safeError(503,'MISSING_API_KEY',null,'configuration',false,cfg.apiKey)}; const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),60000); if(signal) signal.addEventListener('abort',()=>controller.abort(signal.reason),{once:true}); try { const r=await fetch(cfg.endpoint,{method:'POST',signal:controller.signal,headers:{'content-type':'application/json',accept:'application/json',[cfg.authHeader]:`${cfg.authScheme?cfg.authScheme+' ':''}${cfg.apiKey}`},body:JSON.stringify(buildPayload(text,mode,cfg))}); if(!r.ok)return {status:r.status,error:safeError(r.status,`UPSTREAM_HTTP_${r.status}`,null,'upstream-request',true,cfg.apiKey)}; const c=extractContent(await r.json()); return c?{status:200,content:c}:{status:502,error:safeError(502,'UPSTREAM_INVALID_RESPONSE',null,'response-parse',true,cfg.apiKey)}; } catch(e) { const status=controller.signal.aborted?504:502; return {status,error:safeError(status,status===504?'UPSTREAM_TIMEOUT':'UPSTREAM_CONNECTION_ERROR',null,'upstream-request',true,cfg.apiKey)}; } finally {clearTimeout(timer);} }
function quotaFailure(status, body='') { if (status===429 || status===402) return true; const s=String(body).toLowerCase(); return status>=400 && status<600 && ['quota','exhausted','insufficient','credit','balance','额度','配额','余额','超限'].some(k=>s.includes(k)); }
async function callUpstream(cfg, payloadBody, signal) { let r; try { r=await fetch(cfg.endpoint,{method:'POST',headers:{'content-type':'application/json',accept:'application/json',[cfg.authHeader]:`${cfg.authScheme?cfg.authScheme+' ':''}${cfg.apiKey}`},body:payloadBody,signal}); } catch(e) { return {ok:false,status:signal.aborted?504:502,quotaFailure:false,outcome:signal.aborted?'timeout':'network-error',...(signal.aborted?{errorCategory:e instanceof Error?e.name:'AbortError'}:{})}; } if(!r.ok) { let body=''; try {body=await r.text();} catch(e) { return {ok:false,status:r.status,quotaFailure:quotaFailure(r.status),outcome:quotaFailure(r.status)?'quota-fallback':'http-error',errorCategory:e instanceof Error?e.name:'Error'}; } const q=quotaFailure(r.status,body); return {ok:false,status:r.status,quotaFailure:q,outcome:q?'quota-fallback':'http-error'}; } let p; try {p=await r.json();} catch(e) { return {ok:false,status:signal.aborted?504:502,quotaFailure:false,outcome:signal.aborted?'timeout':'unknown-error',errorCategory:e instanceof Error?e.name:'Error'}; } const content=extractContent(p); return content?{ok:true,content,status:r.status,outcome:'success'}:{ok:false,status:502,quotaFailure:false,outcome:'unknown-error'}; }
async function recognizeWithFallbackDebug(primary,fallback,payloadBody,signal,timeouts={primaryTimeoutMs:25000,fallbackTimeoutMs:20000}) { const started=Date.now(), tried=[], attempts=[]; let fallbackReason=null, failedUpstream=null, selectedUpstream=null, finalFailureReason, finalStatus; const run=async(name,cfg,budget)=>{tried.push(name);const t=Date.now(), c=new AbortController();const timer=setTimeout(()=>c.abort(new Error(`${name} timeout`)),budget);const abort=()=>c.abort(signal.reason);if(signal.aborted)c.abort(signal.reason);else signal.addEventListener('abort',abort,{once:true});let r;try{r=await callUpstream(cfg,payloadBody,c.signal);}finally{clearTimeout(timer);signal.removeEventListener('abort',abort);}attempts.push({upstream:name,model:cfg.model,endpoint:cfg.endpoint,status:r.status,durationMs:Date.now()-t,outcome:r.outcome,...(r.errorCategory?{errorCategory:r.errorCategory}:{})});return r;}; const finish=result=>({result,debug:{upstreamTried:tried,selectedUpstream,selectedUpstreamModel:selectedUpstream?(selectedUpstream=== (primary.name||'opencode-go')?primary:fallback).model:null,selectedUpstreamEndpoint:selectedUpstream?(selectedUpstream=== (primary.name||'opencode-go')?primary:fallback).endpoint:null,failedUpstream,fallbackReason,durationMs:Date.now()-started,attempts,...(finalFailureReason?{finalFailureReason}:{}) ,...(finalStatus!==undefined?{finalStatus}:{})}}); const pn=primary.name||'opencode-go',fn=fallback.name||'deepseek'; const first=await run(pn,primary,timeouts.primaryTimeoutMs); if(first.ok){selectedUpstream=pn;return finish({content:first.content});} failedUpstream=pn; if(first.quotaFailure&&fallback.apiKey){fallbackReason='quota';const second=await run(fn,fallback,timeouts.fallbackTimeoutMs);if(second.ok){selectedUpstream=fn;return finish({content:second.content});}failedUpstream=fn;finalFailureReason=second.outcome;finalStatus=second.status;return finish({status:second.status});} finalFailureReason=first.outcome;finalStatus=first.status;return finish({status:first.status}); }
async function recognizeWithFallback(primary,fallback,payloadBody,signal,timeouts){return (await recognizeWithFallbackDebug(primary,fallback,payloadBody,signal,timeouts)).result;}
module.exports={DEFAULT_ENDPOINT,DEFAULT_MODEL,SYSTEM_PROMPT,STRUCTURE_SYSTEM_PROMPT,REPORT_STRUCTURE_SYSTEM_PROMPT,normalizeEndpoint,config,buildPayload,extractContent,clean,errorMessage,safeError,recognize,quotaFailure,callUpstream,recognizeWithFallback,recognizeWithFallbackDebug};
